#+TITLE: 第一章 JavaScript 基础

* 第一章 JavaScript 基础

** JavaScript 脚本

   Node 是 JavaScript 的运行时，因此它可以运行 JavaScript 脚本。

   JavaScript 脚本以 =.js= 结尾，除此之外， Node 还支持以 =.mjs= 结尾的脚本。 Node 本身是不支持 TS 、 Vue 、 JSX 等扩展语言的。

   #+BEGIN_QUOTE
   对于一些初学者来说，可能理不清楚 Node 与 TS 、 Vue 、 JSX 等的关系，简单来说，我们是基于 Node 再构建了一个编译器，用这个编译器将 TS 等编译成 JavaScript 。当然，至于这些 JavaScript 能否运行于 Node 之上是另一回事了。从中我们管窥到一点，构筑现代前端的一大基础技术原理，就是编译原理。不管你愿不愿意，还是要学的。
   #+END_QUOTE

   JavaScript 是一门历史负担挺重的语言，我们尽量摒弃一些不良的实践，教授一个干净、现代的 JavaScript 。

** JavaScript 基本数据类型

   JavaScript 是一门弱类型语言，且目前也没有类型标注。弱类型一方面提供给 JavaScript 以极大的自由，但另一方面，在工程扩大化之后， JavaScript 过于灵活的特性不利于 API 使用的约束。面对这个问题，我们可以选择使用 TypeScript 进行编译器约束，或者借助 JsDoc 等工具，并加上良好的编程习惯来做约束。

   JavaScript 的基本数据类型主要有 string 、 number 、 boolean 、 object 、 null 、 undefined 等，你可能还听说过 bigint 和 symbol ，这两个也是基本类型，不过一些老版本的 Node 会不支持，但最新版都支持了。

*** 数字类型

    对于基础类型，我们可以通过 =typeof= 操作符获取值的具体类型。例如， =typeof 1= 获得的就是 ='number'= 。

    JavaScript 标准不区分浮点数和整数，但 V8 引擎还是会区分的，因此整数还是可以放心用的。 JavaScript 的数字范围我们可以通过 =Number.MAX_VALUE= 和 =Number.MIN_VALUE= 查看。

    JavaScript 中出了正常的数字之外，还有两个特殊数字，一个是 =NaN= ，另一个是 =Infinity= 。任何数除以 =0= 得到 =Infinity= ，且区分正负。 =NaN= 意为不是 number ，任意两个 =Infinity= 之间进行计算可得 =NaN= ，又或者一个强制类型转换失败的数也是 =NaN= 。

    =NaN= 是一个逃避不了的坑。 =NaN= 与任何数都不相等，包括它自己，检测 =NaN= 的方法一般是使用 =isNaN= 。

*** 字符串类型

    字符串类型是我们经常打交道的类型，我们常常处理它，然后又将它转换为其他各种类型。

    在 JavaScript 中，只有字符串类型，没有字符类型。但我们也可以像取数组里的元素一样取取出里面里面的字符，成为一个仅仅包含一个字符的字符串。比如：

    #+BEGIN_SRC javascript
    let a = '1000';
    console.log(a[2]); // 0
    #+END_SRC

    但我们不能对它进行赋值，这点需要注意。

    在 JavaScript 中，我们可以使用 =''= 、 =""= 、 =``= 。其中 =``= 比较特别，它是字符串模板，可以很方便的进行字符串格式化。

    #+BEGIN_SRC javascript
    const a = 12;
    console.log(`a = ${a}`); // a = 12
    #+END_SRC

*** 布尔类型

    JavaScript 的布尔类型值是 =true= 、 =false= 。

*** =null= 、 =undefined= 类型

    =null= 和 =undefined= 都代表值不存在， =undefined= 代表值未定义。

    需要注意的一点是， =typeof null= 的值为 ='object'= 。

    #+BEGIN_SRC javascript
    let a; // 此时 a 为 undefined
    a = null; // null 类型值就是 null
    #+END_SRC

*** 对象类型

    除开其他基础类型，剩下的就是对象类型。在 JavaScript 中，数组和各种复合结构都是对象类型。也就是说，在 JavaScript 中，所有类型都在基本类型的范围内。

    我们想要创建一个对象类型，常见的包括数组、字典、构造函数等等。

    #+BEGIN_SRC javascript
    const obj = {}; // 字典
    const arr = []; // 数组
    const date = new Date(); // 构造函数
    #+END_SRC

    我们着重讲讲一下前两个。

**** 字典结构

     字典结构是一个非常重要的结构，我们用得非常多。

     #+BEGIN_SRC javascript
     const obj = {
        'hello': 'world!',
        hi: 1,
        fn: () => console.log('hello'),
        map: {
            a: 1,
        },
     };
     #+END_SRC

     在 JavaScript 中，字典并不限制键名与键值的类型。键名默认是字符串，因此键名写作 ='hello'= 和 =hello= 都是一样的。

     如果我们需要使用其他类型作为键名，则需要用到 =[]= 。

     #+BEGIN_SRC javascript
     const k = {};
     const obj = {
        'hello world': 'jack',
        [k]: 'b',
     };
     #+END_SRC

     需要注意的是，当我们作键名的字符串带空格时，引号不能去掉。

**** 数组结构
